[package]
name = "cqrs-performance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cqrs-library = { path = "../cqrs-library" }
cqrs-kafka = { path = "../cqrs-kafka" }
serde = { workspace = true }
config ={ workspace = true }

log = { workspace = true }
env_logger = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

# Performance testing dependencies
hdrhistogram = "7.5"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
