command_topic = "TEST"
response_topic = "TEST_RESPONSE"
events_topic = "TEST_EVENTS"
bootstrap_server = "127.0.0.1:9092"
transaction_id = "transaction_id"
service_id = "service_id"
log_level = "info"
