[package]
name = "cqrs-kafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cqrs-library = { path = "../cqrs-library" }
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
log = "0.4.8"
blockingqueue = "0.1.1"
futures = "0.3.28"
async-trait = { version = "0.1.75", features = [] }
serde = { version = "1.0.193", features = ["derive"] }
config = "0.14.0"

[dev-dependencies]
testcontainers = "0.15.0"
testcontainers-modules =  { version = "0.3.2", features = ["kafka"]}
env_logger = "0.11.1"
tokio = { version = "1.35.0", features = ["macros", "rt-multi-thread", "time", "sync"] }
typetag = "0.2"
wait-for-me = "0.3.0"
